#### Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute: Mean Median Standard deviation Variance (for each feature)
3. Identify: Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [41]:
from sklearn.datasets import load_iris
import numpy as np

In [42]:
iris = load_iris() #loads data as dict

In [43]:
# Extract feature matrix as NumPy array
feature_matrix = iris.data # extracting feature
print("Feature Matrix Shape :" ,feature_matrix.shape)
print("Feature Matrix row :" ,feature_matrix[0])

Feature Matrix Shape : (150, 4)
Feature Matrix row : [5.1 3.5 1.4 0.2]

In [44]:
# Extract feature names - remove
feature_names = iris.feature_names
print("Feature Names:",feature_names)

Feature Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [45]:
# Mean Median Standard deviation Variance (for each feature)
mean = np.mean(feature_matrix,axis=0)
median = np.median(feature_matrix,axis=0)
std=np.std(feature_matrix,axis=0)
variance=np.argmax(np.var(feature_matrix,axis=0))
print("Mean:",mean)
print("Median:",median)
print("SD:",std)
print("Variance:",variance)

print("Max Variance:",np.argmax(variance))

Mean: [5.84333333 3.05733333 3.758      1.19933333]
Median: [5.8  3.   4.35 1.3 ]
SD: [0.82530129 0.43441097 1.75940407 0.75969263]
Variance: 2
Max Variance: 0

##### Identify: Which feature has highest variability and why it matters in ML

1. Petal_length has the highest variance in the feature matrix.
2. It means data is more spread, not constant and so we have more information.
3. When variance is more that means the model can learn patterns better.

In [46]:
#Convert any one feature into shape (n,1) and explain why ML models expect this format

petal_width = feature_matrix[:,3]
print(petal_width.shape)

petal_width_reshape = petal_width.reshape(-1,1)
print(petal_width_reshape.shape)

(150,)
(150, 1)

In [47]:
# (150,) → just a list
# (150,1) → proper column matrix
# Most models expect data in 2D format

#### Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract: First 100 samples Only last 2 features
2. Use boolean masking: Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [48]:
print("First 100 samples and last two features")
feature_matrix[:100,-2:].shape

First 100 samples and last two features

(100, 2)

In [49]:
print("Feature Names:",feature_names)

Feature Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [50]:
print("Samples where petal length is greater than dataset mean")
print("Mean of feature matrix:",np.mean(feature_matrix))
samples = feature_matrix[feature_matrix[:,2] > np.mean(feature_matrix),2]

print("Shape:",samples.shape)
print("Count:",np.sum(samples))

Samples where petal length is greater than dataset mean
Mean of feature matrix: 3.4644999999999997
Shape: (97,)
Count: 481.0

### Feature Selection
Instead of feeding all raw data, you select important features
Here: only petal-related features.
ML models don’t learn from all data blindly,they learn from carefully selected features and filtered samples.

👉 Helps:

1. Reduce noise
2. Improve model accuracy
3. Faster training
4. Data Filtering / Preprocessing
    . Removed samples below average petal length
    . This is similar to:
        . Removing outliers
        . Selecting specific segments (e.g., high-value customers)
5. Boolean Masking = Real ML Data Pipelines

    This exact logic is used in:

    a. Fraud detection → transactions > threshold
    b. Healthcare → patients with certain metrics
    c. Finance → stocks above moving average

#### Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization: X-mean/Std
 
2. Verify: Mean ≈ 0 Std ≈ on

In [51]:
mean = np.mean(feature_matrix,axis=0) #columnwise
std = np.std(feature_matrix,axis=0) #columnwise

In [52]:
standardized_matrix = (feature_matrix - mean) / std
# print("standardization:",standardization)


# Mean before standardization
print("Mean before scaling:", np.mean(feature_matrix, axis=0))

# Std before standardization
print("Std before scaling:", np.std(feature_matrix, axis=0))

# Mean after standardization
print("Mean after scaling:", np.mean(standardized_matrix , axis=0))

# Std after standardization
print("Std after scaling:", np.std(standardized_matrix , axis=0))

Mean before scaling: [5.84333333 3.05733333 3.758      1.19933333]
Std before scaling: [0.82530129 0.43441097 1.75940407 0.75969263]
Mean after scaling: [-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
Std after scaling: [1. 1. 1. 1.]

#### Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display: head(), tail() info(), describe()
2. Identify: Missing values per column Numerical vs categorical features
3. Explain: Why identifying feature types is important before modeling

In [53]:
import seaborn as sns

# Load dataset
df = sns.load_dataset('titanic')

#print(df.head())
#print(df.tail())
#print(df.info())
#print(df.describe())

# Missing values per column Numerical vs categorical features
import numpy as np

# Numerical features
numerical_cols = df.select_dtypes(include=[np.number]).columns
num_data_missing = df[numerical_cols].isnull().sum()

# Categorical features
categorical_cols = df.select_dtypes(include=['object', 'category', 'bool']).columns
cat_data_missing = df[categorical_cols].isna().sum()

print("Numerical Columns:\n", numerical_cols)
print("\n")
print("Missing values per column for Numerical Columns:\n", num_data_missing)
print("\n")
print(num_data_missing[num_data_missing>0])
print("\n")
print("*****************************************************************************************************")
print("\nCategorical Columns:\n", categorical_cols)
print("\n")
print("Missing values per column for Categorical Columns:\n", cat_data_missing)
print("\n")
print(cat_data_missing[cat_data_missing>0])
print("\n")

Numerical Columns:
 Index(['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare'], dtype='object')


Missing values per column for Numerical Columns:
 survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64


age    177
dtype: int64


*****************************************************************************************************

Categorical Columns:
 Index(['sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')


Missing values per column for Categorical Columns:
 sex              0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


embarked         2
deck           688
embark_town      2
dtype: int64

#### Why identifying feature types is important before modeling
1. Different Data Types Need Different Preprocessing
2. Models Only Understand Numbers - convert categorical → numeric before training
3. Helps Choose the Right Model
4. Prevents Logical Errors
5. Better Feature Engineering

#### Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter: Female passengers in 1st class
2. Compute: Survival rate for this group
3. Compare with overall survival rate
4. Interpret: What insight can be used in ML feature engineering

In [54]:
df.head()
female_pass_first_class = df[(df["sex"] == "female") & (df["pclass"]==1)]

print("Female passengers in 1st class:\n",female_pass_first_class.head())

print("\nSurvival rate for this group:\n",female_pass_first_class["survived"].mean())

print("\nOverall survival rate\n",df["survived"].mean())

Female passengers in 1st class:
     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1          1       1  female  38.0      1      0   71.2833        C  First
3          1       1  female  35.0      1      0   53.1000        S  First
11         1       1  female  58.0      0      0   26.5500        S  First
31         1       1  female   NaN      1      0  146.5208        C  First
52         1       1  female  49.0      1      0   76.7292        C  First

      who  adult_male deck  embark_town alive  alone
1   woman       False    C    Cherbourg   yes  False
3   woman       False    C  Southampton   yes  False
11  woman       False    C  Southampton   yes   True
31  woman       False    B    Cherbourg   yes  False
52  woman       False    D    Cherbourg   yes  False

Survival rate for this group:
 0.9680851063829787

Overall survival rate
 0.3838383838383838

#### Interpret: What insight can be used in ML feature engineering
The survival rate for the females in first class is very high compared to overall survival rate

#### Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain: Why different strategies are used for different columns

In [22]:
df["age"].fillna(df["age"].median(),inplace=True)
df["embarked"].fillna(df["embarked"].mode(),inplace=True)
#df.drop(columns=["deck"],inplace=True)
print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

#### Why Different Strategies Are Used

This is the most important part 👇

1. Numerical Data (age) → Use Median

    Why median?

    Robust to outliers
    Age data can be skewed (few very old passengers)

    Mean can get distorted
    Median gives a more realistic central value

2. Categorical Data (embarked) → Use Mode

    Why mode?

    Categorical data = labels (not numbers)
    You can’t take mean/median of "S", "C", "Q"

    Mode = most frequent category
    Safest assumption for missing values

3. High Missing Data (deck) → Drop Column

    Why drop?

    Too many missing values (~75%+)
    Filling would introduce too much noise

    Better to remove than corrupt the dataset


#### Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create: family_size = sibsp + parch + 1
2. Create: is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain: Why engineered features improve ML models

In [23]:
df["family_size"] = df["sibsp"] + df["parch"] + 1

In [24]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1

In [25]:
df["is_alone"] = df["alone"].astype(int)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,is_alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1,1

In [26]:
df.groupby("is_alone")["survived"].mean()

is_alone
0    0.505650
1    0.303538
Name: survived, dtype: float64

#### Explain: Why engineered features improve ML models
Feature engineering = turning raw data into meaningful signals that make learning easier for the model.
1. Capture Hidden Patterns
2. Simplify Learning for the Model by giving a direct, meaningful feature
3. Improve model performance

#### Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute: Average tip by day Total bill by gender
2. Create new feature: tip_percentage
3. Identify: Which day has highest tipping behavior
4. Explain: How this helps in segmentation models

In [27]:
import seaborn as sns

tips_data = sns.load_dataset('tips')
tips_df = tips_data.copy()

In [28]:
tips_df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
print("Average tip by day\n",tips_df.groupby('day')["tip"].mean())

Average tip by day
 day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [30]:
tips_df["tip_percentage"] = (tips_df["tip"]/tips_df["total_bill"]) * 100
tips_df.head()

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765

In [31]:
print("Total bill by gender\n",tips_df.groupby("sex")["tip"].sum())

Total bill by gender
 sex
Male      485.07
Female    246.51
Name: tip, dtype: float64

In [32]:
tipping_percentage_by_day = tips_df.groupby("day")["tip"].mean()
print("Day with highest tipping behavior: ",tipping_percentage_by_day.idxmax())

Day with highest tipping behavior:  Sun

#### Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter: total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze: Is this segment under-tipping?
4. Explain: How such filtering helps anomaly detection

In [33]:
tips_df.head()
tips_filtered_data = tips_df[(tips_df["total_bill"] > 20) & (tips_df["tip"] < 3)]
print("total_bill > 20 AND tip < 3:",tips_filtered_data[["total_bill","tip","tip_percentage"]].head())

total_bill > 20 AND tip < 3:     total_bill   tip  tip_percentage
21       20.29  2.75       13.553475
33       20.69  2.45       11.841469
48       28.55  2.05        7.180385
57       26.41  1.50        5.679667
68       20.23  2.01        9.935739

In [34]:
print("Filtered group avg tipping",tips_filtered_data["tip_percentage"].mean())

Filtered group avg tipping 9.08275278162947

In [35]:
print("Total avg tipping",tips_df["tip_percentage"].mean())

Total avg tipping 16.080258172250463

1. Yes its under tipping
2. Filtering based on conditions helps you spot patterns that break normal behavior, which is the foundation of anomaly detection.

#### Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform: Vertical stacking Horizontal stacking
3. Reshape into (2,6)
4. Explain: Why reshaping is required in ML pipelines

In [36]:
arr1 = np.array([[1,2],[4,5],[7,9]])
arr2 = np.array([[2,3],[9,8],[1,4]])
print(arr1)
print(arr2)

[[1 2]
 [4 5]
 [7 9]]
[[2 3]
 [9 8]
 [1 4]]

In [37]:
v_stack=np.vstack((arr1,arr2))
print("Vertical Stacking",v_stack)

Vertical Stacking [[1 2]
 [4 5]
 [7 9]
 [2 3]
 [9 8]
 [1 4]]

In [56]:
hstack = np.hstack((arr1,arr2))
print("Horizontal Stacking",hstack)

Horizontal Stacking [[1 2 2 3]
 [4 5 9 8]
 [7 9 1 4]]

In [57]:
v_stack.reshape(2,6)

array([[1, 2, 4, 5, 7, 9],
       [2, 3, 9, 8, 1, 4]])

In [58]:
h_stack.reshape(2,6)

array([[1, 2, 2, 3, 4, 5],
       [9, 8, 7, 9, 1, 4]])

#### Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array
Output:

Final feature matrix ready for model training

In [59]:
import seaborn as sns

In [60]:
#load dataset
titanic = sns.load_dataset("titanic")

In [61]:
titanic.shape

(891, 15)

In [64]:
# Handle missing values
titanic.info()
titanic.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [65]:
titanic['age'].fillna(titanic['age'].median(), inplace=True)
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [66]:
titanic.drop(columns=['deck'], inplace=True)

In [67]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

In [68]:
import pandas as pd

# Encode 'sex' (binary) and embarked
titanic['sex'] = titanic['sex'].map({'male': 0, 'female': 1})
# One-hot encode 'embarked'
titanic = pd.get_dummies(titanic, columns=['embark_town'], drop_first=True)
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive,alone,embark_town_Queenstown,embark_town_Southampton
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,no,False,0,1
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,yes,False,0,0
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,yes,True,0,1
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,yes,False,0,1
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,no,True,0,1

In [71]:
features = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 
            'embark_town_Queenstown', 'embark_town_Southampton']

X = titanic[features]
print(X)

     pclass  sex   age  sibsp  parch     fare  embark_town_Queenstown  \
0         3    0  22.0      1      0   7.2500                       0
1         1    1  38.0      1      0  71.2833                       0
2         3    1  26.0      0      0   7.9250                       0
3         1    1  35.0      1      0  53.1000                       0
4         3    0  35.0      0      0   8.0500                       0
..      ...  ...   ...    ...    ...      ...                     ...
886       2    0  27.0      0      0  13.0000                       0
887       1    1  19.0      0      0  30.0000                       0
888       3    1  28.0      1      2  23.4500                       0
889       1    0  26.0      0      0  30.0000                       0
890       3    0  32.0      0      0   7.7500                       1

     embark_town_Southampton
0                          1
1                          0
2                          1
3                          1
4                          1
..                       ...
886                        1
887                        1
888                        1
889                        0
890                        0

[891 rows x 8 columns]

In [72]:
# Normalize numerical features
mean = X.mean()
std = X.std()

In [73]:
X_scaled = (X-mean)/std

In [74]:
#Convert to NumPy Array
X_final = X_scaled.to_numpy()

print("Final shape:", X_final.shape)
print(X_final[:5])

Final shape: (891, 8)
[[ 0.82691282 -0.73728105 -0.5654189   0.43255043 -0.47340772 -0.50216314
  -0.3073897   0.61895873]
 [-1.56522783  1.35481262  0.66348839  0.43255043 -0.47340772  0.78640362
  -0.3073897  -1.61380333]
 [ 0.82691282  1.35481262 -0.25819208 -0.47427882 -0.47340772 -0.48857985
  -0.3073897   0.61895873]
 [-1.56522783  1.35481262  0.43306827  0.43255043 -0.47340772  0.42049407
  -0.3073897   0.61895873]
 [ 0.82691282 -0.73728105  0.43306827 -0.47427882 -0.47340772 -0.48606443
  -0.3073897   0.61895873]]

#### Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain: Impact on overfitting and model performance

In [87]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [78]:
corr_matrix = iris_df.corr()
print(corr_matrix)

                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754
sepal width (cm)           -0.117570          1.000000          -0.428440
petal length (cm)           0.871754         -0.428440           1.000000
petal width (cm)            0.817941         -0.366126           0.962865

                   petal width (cm)
sepal length (cm)          0.817941
sepal width (cm)          -0.366126
petal length (cm)          0.962865
petal width (cm)           1.000000

In [79]:
# Identify highly correlated features
# petal_length and petal_width ~ 0.96

In [80]:
iris_df['target'] = iris.target

# Correlation with target
target_corr = iris_df.corr()['target'].abs()
print(target_corr)
#Both petal length and petal width have almost same target corelation

sepal length (cm)    0.782561
sepal width (cm)     0.426658
petal length (cm)    0.949035
petal width (cm)     0.956547
target               1.000000
Name: target, dtype: float64

In [81]:
iris_df.isnull().sum() #Both petal length and petal width have 0 missing values again a tie

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [82]:
iris_df.var()  #Higher variance more data

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
target               0.671141
dtype: float64

In [84]:
iris_df = iris_df.drop(columns=["petal width (cm)"])

In [86]:
iris_df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  target
0                5.1               3.5                1.4       0
1                4.9               3.0                1.4       0
2                4.7               3.2                1.3       0
3                4.6               3.1                1.5       0
4                5.0               3.6                1.4       0

#### Impact of over fitting on model performance
Overfitting happens when a model learns the training data too well, including noise and random patterns.
Impact - Fails on new/real data

#### Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group: Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret: Which segment has highest survival likelihood

In [93]:
#Create age group
def get_age_group(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

In [94]:
#use .apply()

titanic['age_group'] = titanic['age'].apply(get_age_group)

In [96]:
titanic["age_group"].head()

0    Adult
1    Adult
2    Adult
3    Adult
4    Adult
Name: age_group, dtype: object

In [99]:
#Compute survival rate per group
survival_by_age_group = titanic.groupby("age_group")["survived"].mean()
print(survival_by_age_group)

age_group
Adult     0.364362
Child     0.539823
Senior    0.269231
Name: survived, dtype: float64

In [100]:
#Interpretation - children have the most likelihood of survival

#### Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute: Mean Standard deviation
3. Identify outliers: Using mean ± 2*std
4. Explain: What high variance means in model performance

In [116]:
import numpy as np
#Generate 1000 random error values using NumPy
error_values = np.random.randn(1000)

In [117]:
mean_error = error_values.mean()
std_error = error_values.std()

print("Mean:",mean_error)
print("Standard Deviation:",std_error)

Mean: -0.01024236654101995
Standard Deviation: 0.9817062582664111

In [118]:
#Identify outliers: Using mean ± 2*std
lower_bound = mean_error - 2 * std_error
upper_bound = mean_error + 2 * std_error

outliers = error_values[(error_values < lower_bound) | (error_values > upper_bound)]

print("Number of outliers:", len(outliers))

Number of outliers: 56

#### Explain: What high variance means in model performance
Variance in MODEL (Prediction Stability) is Bad

This is about how much the model’s predictions change

Example:
Same input → very different outputs
Model behaves inconsistently

Model is unstable
Often overfitting
Poor generalization

In the above case 56 outliers which is almost 5% and is acceptable

#### Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create: tip_percentage
2. Group by: day and time
3. Identify: Highest revenue segment
4. Provide: Recommendation for business strategy How ML model can use this insight

In [119]:
tips_df.head()

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765

In [126]:
tips_df["day"]
grouped = tips_df.groupby(["day", "time"]).agg({
    "total_bill": "sum",
    "tip_percentage": "mean"
})

print(grouped)

             total_bill  tip_percentage
day  time
Thur Lunch      1077.55       16.130074
     Dinner       18.78       15.974441
Fri  Lunch        89.92       18.876489
     Dinner      235.96       15.891611
Sat  Lunch         0.00             NaN
     Dinner     1778.40       15.315172
Sun  Lunch         0.00             NaN
     Dinner     1627.16       16.689729

In [130]:
grouped = tips_df.groupby(['day', 'time']).agg({
    'total_bill': 'sum',
    'tip_percentage': 'mean'
})

print(grouped)

             total_bill  tip_percentage
day  time
Thur Lunch      1077.55       16.130074
     Dinner       18.78       15.974441
Fri  Lunch        89.92       18.876489
     Dinner      235.96       15.891611
Sat  Lunch         0.00             NaN
     Dinner     1778.40       15.315172
Sun  Lunch         0.00             NaN
     Dinner     1627.16       16.689729

Dinner on weekends (Sat/Sun) generates highest revenue
Lunch segments have lower total bills